FROM node:16.18.0-alpine3.16 AS builder

WORKDIR /

COPY ["package.json", "package-lock.json", "tsconfig.json", "./"]
COPY [".env", ".env"]

COPY ./src ./src

RUN npm ci
RUN npm run build

FROM node:16.18.0-alpine3.16

WORKDIR /usr/src/app

COPY --from=builder ["/package.json", "/package-lock.json", "./"]
COPY --from=builder ./dist ./dist

RUN npm ci --omit=dev
CMD node dist/index.js
