version: '3.8'
services:
  proxy:
    container_name: nginx
    image: jonasal/nginx-certbot:4.2.0-nginx1.23.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - DEBUG=${DEBUG}
      - USE_LOCAL_CA=${USE_LOCAL_CA}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/local_ca
      - dev_nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - server
  server:
    container_name: api
    restart: always
    build: .
    env_file: ./.env
    # environment:
    #   - DIRECT_URL=${DIRECT_URL}
    #   - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PORT}:8080"
      - 9229:9229
    # depends_on:
    #   - db
    #   - cache
    volumes:
      - ./src:/usr/app/src
#   db:
#     container_name: postgres
#     image: postgres:16.1-alpine
#     restart: always
#     ports:
#       - '${PGPORT}:${PGPORT}'
#     volumes:
#       - data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_PASSWORD=${PGPASSWORD}
#       - POSTGRES_DB=${PGDATABASE}
#       - POSTGRES_USER=${PGUSER}
#   cache:
#     image: redis:6.2-alpine
#     restart: always
#     ports:
#       - "${REDIS_PORT}:${REDIS_PORT}"
#     command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
#     volumes:
#       - cache:/data
volumes:
  data: {}
  dev_nginx_secrets: {}
#   cache:
#     driver: local
