version: '3.8'
services:
  nginx:
    image: jonasal/nginx-certbot
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - STAGING=${STAGING}
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./data/nginx/user_conf.d:/etc/nginx/user_conf.d
  waterlog-api:
    container_name: waterlog
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - waterlog-db
  waterlog-db:
    container_name: waterlog-db
    image: postgres
    restart: always
    ports:
      - '${PGPORT}:${PGPORT}'
    volumes:
      - prod_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
volumes:
  prod_data: {}
  nginx_secrets: {}
