version: '3.8'
services:

  api:
    container_name: waterlog
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
  waterlog-db:
    container_name: waterlog-db
    image: postgres
    restart: always
    ports:
      - '${PGPORT}:${PGPORT}'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
volumes:
  data: {}
