version: '3.8'
services:
  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot:4.2.0-nginx1.23.3
    restart: unless-stopped
    env_file: ./.env.production
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - STAGING=${STAGING}
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - api
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.production
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - waterlog-db
  waterlog-db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '${PGPORT}:${PGPORT}'
    volumes:
      - prod_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
volumes:
  prod_data: {}
  nginx_secrets: {}
