version: "3.8"
services:
  lambda:
    container_name: waterlog
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.production
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - cache
      - db
  db:
    container_name: postgres
    image: postgres:16.1-alpine
    restart: always
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - prod_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
  cache:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
