version: '3.8'
services:
  # gateway-dev:
  #   container_name: gateway-dev
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.sam
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ${PWD}:${PWD}
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   depends_on:
  #     - lambda-dev
  #   command: sam local start-api -v "${PWD}/.aws-sam/build" --host=0.0.0.0 --container-host=host.docker.internal.com --container-host-interface=127.0.0.1
  lambda-dev:
    container_name: graphql-dev
    restart: always
    build: .
    env_file: ./.env
    environment:
      - DIRECT_URL=${DIRECT_URL}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PORT}:8080"
      - 9229:9229
    depends_on:
      - db-dev
      - cache-dev
    volumes:
      - ./src:/usr/app/src
  db-dev:
    container_name: postgres
    image: postgres:16.1-alpine
    restart: always
    ports:
      - '${PGPORT}:${PGPORT}'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
  cache-dev:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
volumes:
  data: {}
  cache:
    driver: local
