"""
Date scalar used for JS Date
"""
scalar Date

"""
Icon scalar mapped to FontAwesome `IconName` type
"""
scalar Icon


"""
Sort Enum
"""
enum Sort {
  ASC
  DESC
}

"""
Sorting input for Drinks
"""
input DrinkSort {
  name: Sort
  createdAt: Sort
}

"""
Drink Interface for all drinks
"""
interface Drink {
  id: ID!
  name: String!
  icon: Icon!
  coefficient: Float
  caffeine: Float
  sugar: Float
  entries: [Entry!]
  user: User
  createdAt: Date!
}

"""
Base Drink used for all drinks
"""
type BaseDrink implements Drink {
  id: ID!
  name: String!
  icon: Icon!
  coefficient: Float
  caffeine: Float
  sugar: Float
  entries: [Entry!]
  user: User
  createdAt: Date!
}

"""
Mixed Drink when drink has ingredients
"""
type MixedDrink implements Drink {
  id: ID!
  name: String!
  icon: Icon!
  coefficient: Float
  caffeine: Float
  sugar: Float
  entries: [Entry!]
  user: User
  ingredients: [Ingredient!]!
  createdAt: Date!
}

"""
Union of Mixed and Base Drinks
"""
union DrinkResult = BaseDrink | MixedDrink

"""
Base Ingredient used in Drink type
"""
type Ingredient {
  id: ID!
  parts: Int!
  drink: DrinkResult
}


"""
Sorting input for Entries
"""
input EntrySort {
  timestamp: Sort
  drink: Sort
  volume: Sort
}

"""
Base Entry for logged drinks
"""
type Entry {
  id: ID!
  volume: Float!
  caffeine: Float!
  sugar: Float!
  waterContent: Float!
  user: User
  drink: DrinkResult
  timestamp: Date!
}

"""
Drink History to retreive summary of drink entries
"""
type DrinkHistory {
  id: ID!
  count: Int!
  totalVolume: Float!
  waterVolume: Float!
  lastEntry: Date
  entries(
    sort: EntrySort,
    distinct: Boolean,
    before: String,
    after: String,
    first: Int,
    last: Int,
    limit: Int,
    drinkId: ID
  ): EntriesPaginated
  drink: DrinkResult!
}

"""
Base user type
"""
type User {
  id: ID!
}

"""
Input for Ingredient type
"""
input IngredientInput {
  drinkId: ID!
  parts: Int!
}

"""
Input for Drink type
"""
input DrinkInput {
  name: String!
  icon: Icon!

  servingSize: String
  caffeine: String
  sugar: String
  coefficient: String

  ingredients: [IngredientInput!]
}

"""
Pagination List metadata
"""
type PageInfo {
  startCursor: String
  endCursor: String
  hasNextPage: Boolean
  hasPreviousPage: Boolean
}

"""
Interface for paginated queries
"""
interface PaginatedQuery {
  pageInfo: PageInfo
}

"""
Edge for Paginated Drinks
"""
type DrinkEdge {
  node: DrinkResult!
  cursor: String
}

"""
Paginated list of drinks
"""
type DrinksPaginated implements PaginatedQuery {
  edges: [DrinkEdge!]!
  pageInfo: PageInfo
}

"""
Edge for Paginated Entries
"""
type EntryEdge {
  node: Entry!
  cursor: String
}

"""
Paginated list of entries
"""
type EntriesPaginated implements PaginatedQuery {
  edges: [EntryEdge!]!
  pageInfo: PageInfo
}

"""
Edge for Paginated Drink History
"""
type DrinkHistoryEdge {
  node: DrinkHistory!
  cursor: String!
}

"""
Paginated Drinks History list
"""
type DrinksHistoryPaginated implements PaginatedQuery {
  edges: [DrinkHistoryEdge!]!
  pageInfo: PageInfo
}

"""
Root Queries
"""
type Query {
  """ Get a drink by id """
  drink(drinkId: ID!): DrinkResult
  drinks(
    sort: DrinkSort,
    search: String,
    before: String,
    after: String,
    first: Int,
    last: Int,
    userId: ID
  ): DrinksPaginated
  entries(
    sort: EntrySort,
    distinct: Boolean,
    before: String,
    after: String,
    first: Int,
    last: Int,
    limit: Int,
    drinkId: ID
  ): EntriesPaginated
  users: [User!]
  me: User
  user(userId: ID!): User
  drinkHistory(drinkId: ID!): DrinkHistory
  drinksHistory(
    before: String,
    after: String,
    first: Int,
    last: Int
  ): DrinksHistoryPaginated
}

"""
Root Mutations
"""
type Mutation {
  entryCreate(volume: Float!, drinkId: ID!): Entry
  drinkCreate(drinkInput: DrinkInput!): DrinkResult
  drinkDelete(drinkId: ID!): DrinkResult
}
