"""
Date scalar used for JS Date
"""
scalar Date

"""
Icon scalar mapped to FontAwesome `IconName` type
"""
scalar Icon


"""
Drink Interface for all drinks
"""
interface DrinkInterface {
  id: ID!
  name: String!
  icon: Icon!
  coefficient: Float
  caffeine: Float
  sugar: Float
  entries: [Entry!]
  user: User
}

"""
Base Drink used for all drinks
"""
# eslint-disable-next-line @graphql-eslint/no-unreachable-types
type BaseDrink implements DrinkInterface {
  id: ID!
  name: String!
  icon: Icon!
  coefficient: Float
  caffeine: Float
  sugar: Float
  entries: [Entry!]
  user: User
}

"""
Mixed Drink when drink has ingredients
"""
# eslint-disable-next-line @graphql-eslint/no-unreachable-types
type MixedDrink implements DrinkInterface {
  id: ID!
  name: String!
  icon: Icon!
  coefficient: Float
  caffeine: Float
  sugar: Float
  entries: [Entry!]
  user: User
  ingredients: [Ingredient!]!
}

"""
Union of Mixed and Base Drinks
"""
union Drink = BaseDrink | MixedDrink

"""
Base Ingredient used in Drink type
"""
type Ingredient {
  id: ID!
  parts: Int!
  drink: Drink
}

"""
Base Entry for logged drinks
"""
type Entry {
  id: ID!
  volume: Float!
  caffeine: Float!
  sugar: Float!
  waterContent: Float!
  user: User
  drink: Drink
  timestamp: Date!
}

"""
Drink History to retreive summary of drink entries
"""
# eslint-disable-next-line
type DrinkHistory {
  count: Int!
  totalVolume: Float!
  waterVolume: Float!
  lastEntry: Date
  drink: Drink!
}

"""
Base user type
"""
type User {
  id: ID!
}

"""
Input for Ingredient type
"""
input IngredientInput {
  drinkId: ID!
  parts: Int!
}

"""
Input for Drink type
"""
input DrinkInput {
  name: String!
  icon: Icon!

  servingSize: String
  caffeine: String
  sugar: String
  coefficient: String

  ingredients: [IngredientInput!]
}

"""
Pagination List metadata
"""
type PageInfo {
  endCursor: String
  hasNextPage: Boolean
}

"""
Interface for paginated queries
"""
interface PaginatedQuery {
  pageInfo: PageInfo
}

"""
Edge for Paginated Drinks
"""
type DrinkEdge {
  node: Drink!
  cursor: String
}

"""
Paginated list of drinks
"""
type DrinksPaginated implements PaginatedQuery {
  edges: [DrinkEdge!]!
  pageInfo: PageInfo
}

"""
Edge for Paginated Entries
"""
type EntryEdge {
  node: Entry!
  cursor: String
}

"""
Paginated list of entries
"""
type EntriesPaginated implements PaginatedQuery {
  edges: [EntryEdge!]!
  pageInfo: PageInfo
}

"""
Root Queries
"""
type Query {
  drink(drinkId: ID!): Drink
  drinks(search: String, cursor: String, limit: Int, userId: ID): DrinksPaginated
  entries(distinct: Boolean, cursor: String, limit: Int, drinkId: ID): EntriesPaginated
  users: [User!]
  currentUser: User
  user(userId: ID!): User
  drinkHistory(drinkId: ID!): DrinkHistory
  drinksHistory: [DrinkHistory]
}

"""
Root Mutations
"""
type Mutation {
  entryCreate(volume: Float!, drinkId: ID!): Entry
  drinkCreate(drinkInput: DrinkInput!): Drink
  drinkDelete(drinkId: ID!): Drink
}
