Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Description: Deployment Environment name
    AllowedValues:
      - dev
      - test
      - prod
      - local
    Default: dev

Resources:
  WaterlogApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      DefinitionBody:
        swagger: '2.0'
        info:
          title: "Waterlog GraphQL API"
          version: "1.0"
        paths:
          /graphql:
            post:
              consumes:
                - application/json
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WaterlogFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
              security:
                - CustomJwksRsaAuthorizer: []
            options:
              responses:
                '204':
                  description: "204 response"
                  headers:
                    Access-Control-Allow-Headers:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Origin:
                      type: "string"
                    Content-Type:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                      method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                    statusCode: '204'
                requestTemplates:
                  application/json: "{ \"statusCode\": 204 }"
                type: mock
                security: []
      Auth:
        Authorizers:
          CustomJwksRsaAuthorizer:
            FunctionArn:
              Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:jwksRsaCustomAuthorizer
            Identity:
              Header: Authorization
              ReauthorizeEvery: 300 # value in seconds

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WaterlogFunction
      Principal: apigateway.amazonaws.com

  WaterlogFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: lambda-dev:test
      Timeout: 30
      ImageConfig:
        Command: ["npm", "start"]
    Metadata:
      Dockerfile: Dockerfile.dev
      DockerContext: .
