Transform: AWS::Serverless-2016-10-31

Resources:
  WaterlogFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["index.handler"]
      Metadata:
        # SkipBuild: True
        Dockerfile: Dockerfile
        DockerContext: .
      Events:
        GraphqlApi:
          Type: Api
          Properties: /graphql
          Method: post

