Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Description: Deployment Environment name
    AllowedValues:
      - dev
      - test
      - prod
      - local
    Default: dev
  AccountId:
    Type: String
    Description: AWS Account ID

Resources:
  WaterlogApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      DefinitionBody:
        swagger: '2.0'
        info:
          title: "Waterlog GraphQL API"
          version: "1.0"
        paths:
          /callback:
            get:
              produces:
                - application/json
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthCallbackFunction.Arn}/invocations

                httpMethod: POST
                type: aws_proxy
              security: []
          /graphql:
            options:
              responses:
                '204':
                  description: "204 response"
                  headers:
                    Access-Control-Allow-Headers:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Origin:
                      type: "string"
                    Content-Type:
                      type: "string"
              x-amazon-apigateway-integration:
                Fn::If:
                  - IsLocalEnvironment
                  - uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OptionsHandlerFunction.Arn}/invocations
                    httpMethod: POST
                    type: aws_proxy
                  - responses:
                      default:
                        responseParameters:
                          method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
                          method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
                          method.response.header.Access-Control-Allow-Origin: "'*'"
                        statusCode: '204'
                    requestTemplates:
                      application/json: "{ \"statusCode\": 204 }"
                    type: mock
              security: []
            post:
              consumes:
                - application/json
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WaterlogFunction.Arn}/invocations
                httpMethod: POST
                type: aws_proxy
              security:
                - CustomJwksRsaAuthorizer: []
        securityDefinitions:
          CustomJwksRsaAuthorizer:
            type: "apiKey"
            name: "Authorization"
            in: "header"
            x-amazon-apigateway-authtype: "custom"
            x-amazon-apigateway-authorizer:
              type: "token"
              authorizerUri:
                Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JwksRsaCustomAuthorizer.Arn}/invocations
              identitySource: "method.request.header.Authorization"
              authorizerResultTtlInSeconds: 300
      Auth:
        Authorizers:
          CustomJwksRsaAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt JwksRsaCustomAuthorizer.Arn
            Identity:
              Header: Authorization
            ReauthorizeEvery: 300 # value in seconds
            Type: TOKEN

  ## functions/authorizer
  JwksRsaCustomAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: functions/authorizer/dist/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Timeout: 60
      MemorySize: 256
      ReservedConcurrentExecutions: 40
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 40
      Environment:
        Variables:
          AUTH0_AUDIENCE: ''
          AUTH0_DOMAIN: ''
          JWKS_URI: ''
      Layers:
        - !Ref RedisLayer

  ## OptionsHandler
  OptionsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.optionsHandler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      CodeUri: functions/options-handler
      Timeout: 30
      MemorySize: 256
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          NODE_ENV: "development"

  ## functions/auth-callback
  AuthCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: functions/auth-callback/dist/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Timeout: 30
      Environment:
        Variables:
          AUTH0_CLIENT_ID: ''
          AUTH0_CLIENT_SECRET: ''
          AUTH0_CALLBACK_URI: ''
          AUTH0_DOMAIN: ''

  ## function/nutritionix-api
  NutritionixApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      PackageType: Zip
      CodeUri: functions/nutritionix-api/dist/
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 30
      Environment:
        Variables:
          NODE_ENV: ''
          NUTRITIONIX_API: ''
          NUTRITIONIX_API_KEY: ''
          NUTRITIONIX_APP_ID: ''

  ## functions/grahql
  WaterlogFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      PackageType: Zip
      CodeUri: functions/graphql
      Handler: dist/index.handler
      Runtime: nodejs20.x
      Timeout: 30
      MemorySize: 512
      Role: !GetAtt WaterlogFunctionRole.Arn
      Environment:
        Variables:
          NODE_ENV: ''
          DATABASE_URL: 'postgresql://admin:password@db:5432/api'
          NUTRITIONIX_LAMBDA: NutritionixApiFunction
          NODE_PATH: /opt/nodejs/node_modules:/var/task/node_modules
          PRISMA_QUERY_ENGINE_LIBRARY: /opt/nodejs/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
      Layers:
       - !Ref PrismaLayer

  ## Prisma Layer
  PrismaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: prisma-layer
      Description: Layer containing Prisma ORM client and extensions
      ContentUri: layers/prisma

  ## Redis Layer
  RedisLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: redis-layer
      Description: Layer containing Redis cache
      ContentUri: layers/redis

  ## Lambda Permissions
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt WaterlogFunction.Arn
      Principal: apigateway.amazonaws.com

  ## Callback Permissions
  CallbackLambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: !GetAtt AuthCallbackFunction.Arn
        Principal: apigateway.amazonaws.com

  WaterlogFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "InvokeNutritionixFunction"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "lambda:InvokeFunction"
                Resource: !GetAtt NutritionixApiFunction.Arn

Conditions:
  IsLocalEnvironment: !Equals [!Ref Environment, local]
