version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    env_file:
      - ../../.env.test
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
