Transform: AWS::Serverless-2016-10-31

Resources:
  WaterlogFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/prod-lambda:latest"
      ImageConfig:
        Command: ["index.handler"]
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
