Transform: AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String

Resources:
  WaterlogFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !If
        - IsLocalEnvironment
        - graphql-fn:latest
        - !Sub "${AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/graphql-fn:dev-v1"
      ImageConfig:
        Command: ["dist/index.handler"]
      Timeout: 30
    Metadata:
      Dockerfile: Dockerfile
      DockerTarget: graphql
      DockerContext: ../..

Outputs:
  WaterlogFunctionArn:
    Description: The ARN of the Auth Callback Function
    Value: !GetAtt [WaterlogFunction, Arn]
    Export:
      Name: !Sub "${AWS::StackName}-WaterlogFunctionArn"

Conditions:
  IsLocalEnvironment: !Equals [!Ref Environment, local]
