Transform: AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String

Resources:
  JwksRsaCustomAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: authorizer-fn:latest
      # ImageUri: !Sub "${AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/prod-lambda:latest"
      ImageConfig:
        Command: ["dist/index.handler"]
    Metadata:
      Dockerfile: Dockerfile
      DockerTarget: authorizer
      DockerContext: ../..

Outputs:
  JwksRsaCustomAuthorizerArn:
    Description: "ARN of the Custom Authorizer Function"
    Value: !GetAtt JwksRsaCustomAuthorizer.Arn
