Transform: AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String

Resources:
  AuthCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: callback-fn:latest
      # ImageUri: !Sub "${AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/prod-lambda:latest"
      ImageConfig:
        Command: ["dist/index.handler"]
    Metadata:
      Dockerfile: Dockerfile
      DockerTarget: auth-callback
      DockerContext: ../..
