Transform: AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String

Resources:
  AuthCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: callback-fn:latest
      ImageConfig:
        Command: ["dist/index.handler"]
    Metadata:
      Dockerfile: Dockerfile
      DockerTarget: auth-callback
      DockerContext: ../..

Outputs:
  AuthCallbackFunctionArn:
    Description: The ARN of the Auth Callback Function
    Value: !GetAtt [AuthCallbackFunction, Arn]
    Export:
      Name: !Sub "${AWS::StackName}-AuthCallbackFunctionArn"
