type Query {
  drink(drinkId: ID!): Drink
  drinks(userId: ID): [Drink]
  ingredient(ingredientId: ID!): Ingredient
  ingredients(drinkId: ID!): [Ingredient]
  entries(drinkId: ID): [Entry]
  users: [User]
  user(userId: ID!): User
}

type Drink {
  id: ID!
  name: String!
  icon: String!
  coefficient: Float
  caffeine: Float
  sugar: Float
  ingredients(drinkId: ID!): [Ingredient]
  entries: [Entry]
}

type Ingredient {
  id: ID!
  parts: Int!
  drink(ingredientId: ID!): Drink
}

type Entry {
  id: ID!
  volume: Float!
  user: User!
  drink: Drink!
  timestamp: String!
}

type User {
  id: ID!
}
